In [8]:
'''The "mpg" dataset, which stands for "miles per gallon". It contains information about various car models and their characteristics, such as cylinders, displacement, horsepower, weight, acceleration, model year, origin, and miles per gallon (mpg) fuel efficiency.

Here's a brief explanation of each column:

mpg: Miles per gallon, representing the fuel efficiency of the car.
cylinders: Number of cylinders in the engine.
displacement: Engine displacement, the measure of the cylinder volume swept by all of the pistons of a piston engine.
horsepower: The power of the engine, typically measured in horsepower (hp).
weight: Weight of the car, often measured in pounds.
acceleration: Acceleration of the car from 0 to 60 miles per hour (mph) in seconds.
model year: Year of manufacturing of the car model.
origin: Origin of the car, represented as a categorical variable (1: USA, 2: Europe, 3: Japan).
name: The name of the car model.
This dataset is commonly used for regression tasks, where the goal is to predict the fuel efficiency (mpg) of a car based on its other characteristics
'''

'The "mpg" dataset, which stands for "miles per gallon". It contains information about various car models and their characteristics, such as cylinders, displacement, horsepower, weight, acceleration, model year, origin, and miles per gallon (mpg) fuel efficiency.\n\nHere\'s a brief explanation of each column:\n\nmpg: Miles per gallon, representing the fuel efficiency of the car.\ncylinders: Number of cylinders in the engine.\ndisplacement: Engine displacement, the measure of the cylinder volume swept by all of the pistons of a piston engine.\nhorsepower: The power of the engine, typically measured in horsepower (hp).\nweight: Weight of the car, often measured in pounds.\nacceleration: Acceleration of the car from 0 to 60 miles per hour (mph) in seconds.\nmodel year: Year of manufacturing of the car model.\norigin: Origin of the car, represented as a categorical variable (1: USA, 2: Europe, 3: Japan).\nname: The name of the car model.\nThis dataset is commonly used for regression tasks, where the goal is to predict the fuel efficiency (mpg) of a car based on its other characteristics\n'

In [68]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')

In [69]:
df = sns.load_dataset('mpg')

In [70]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [71]:
df.drop('name' , axis = 1, inplace = True)

In [72]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,18.0,8,307.0,130.0,3504,12.0,70,usa
1,15.0,8,350.0,165.0,3693,11.5,70,usa
2,18.0,8,318.0,150.0,3436,11.0,70,usa
3,16.0,8,304.0,150.0,3433,12.0,70,usa
4,17.0,8,302.0,140.0,3449,10.5,70,usa

In [73]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,18.0,8,307.0,130.0,3504,12.0,70,usa
1,15.0,8,350.0,165.0,3693,11.5,70,usa
2,18.0,8,318.0,150.0,3436,11.0,70,usa
3,16.0,8,304.0,150.0,3433,12.0,70,usa
4,17.0,8,302.0,140.0,3449,10.5,70,usa

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
dtypes: float64(4), int64(3), object(1)
memory usage: 25.0+ KB

In [75]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [76]:

#Since we have not done outlier treatment so it is better to replace missing value with median

In [77]:
df['horsepower'].median()

93.5

In [78]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].median())

In [79]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [80]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model_year        int64
origin           object
dtype: object

In [81]:
df['origin'].value_counts()

origin
usa       249
japan      79
europe     70
Name: count, dtype: int64

In [82]:
#Data Encoding
#using map USA 1 JAPAN 2 EUROPE 3
df['origin'] = df['origin'].map({'usa' : 1 , 'japan' : 2 , 'europe' : 3})

In [83]:
df['origin']

0      1
1      1
2      1
3      1
4      1
      ..
393    1
394    3
395    1
396    1
397    1
Name: origin, Length: 398, dtype: int64

In [66]:
# df['origin'] = df['origin'].astype(int)

In [84]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model_year        int64
origin            int64
dtype: object

In [85]:
#seperate into X and Y

#Next we have to drop the target 
X = df.drop('mpg',axis = 1 )
Y = df['mpg']

In [86]:
X

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,8,307.0,130.0,3504,12.0,70,1
1,8,350.0,165.0,3693,11.5,70,1
2,8,318.0,150.0,3436,11.0,70,1
3,8,304.0,150.0,3433,12.0,70,1
4,8,302.0,140.0,3449,10.5,70,1
...,...,...,...,...,...,...,...
393,4,140.0,86.0,2790,15.6,82,1
394,4,97.0,52.0,2130,24.6,82,3
395,4,135.0,84.0,2295,11.6,82,1
396,4,120.0,79.0,2625,18.6,82,1
397,4,119.0,82.0,2720,19.4,82,1

In [87]:
Y

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

In [89]:
#train test split

from sklearn.model_selection import train_test_split
X_train , X_test , Y_train , Y_test = train_test_split(X , Y , test_size = 0.3 , random_state = 1)

In [90]:
X_train.shape , X_test.shape

((278, 7), (120, 7))

In [92]:
#Building simple linear regression model
from sklearn.linear_model import LinearRegression
regression_model = LinearRegression()

In [93]:
regression_model

LinearRegression()

In [94]:
regression_model.fit(X_train , Y_train)

LinearRegression()

In [95]:
regression_model.coef_

array([-0.31761423,  0.02623748, -0.01827076, -0.00748775,  0.05040673,
        0.84709514,  1.51909584])

In [96]:
for i, col_name in enumerate (X_train.columns):
    print(f'The coef for {col_name} is {regression_model.coef_[i]}')

The coef for cylinders is -0.3176142302799276
The coef for displacement is 0.02623748259907893
The coef for horsepower is -0.01827076491312441
The coef for weight is -0.007487750398361907
The coef for acceleration is 0.050406734619714726
The coef for model_year is 0.8470951427061371
The coef for origin is 1.5190958387975058

In [97]:
#observations:
#coefficients are relatively smaller, if one independent variable changes
#there will be not much difference in prediction
#This is sometime called as smoother model

#these features might not be contributing in model training

In [98]:
from sklearn.metrics import r2_score

Y_pred_linear = regression_model.predict(X_test)
r2_linear = r2_score(Y_test , Y_pred_linear)
print(f"The R square of linear regression {r2_linear}")

The R square of linear regression 0.8348001123742285

In [99]:
#Regularisation
#Ridge regression

In [101]:
from sklearn.linear_model import Ridge

In [102]:
ridge_regression_model = Ridge(alpha = 0.1)
ridge_regression_model
#in practical implementation lambda is alpha

Ridge(alpha=0.1)

In [103]:
ridge_regression_model.fit(X_train , Y_train)

Ridge(alpha=0.1)

In [104]:
for i, col_name in enumerate (X_train.columns):
    print(f'The coef for {col_name} is {ridge_regression_model.coef_[i]}')

The coef for cylinders is -0.317003210100651
The coef for displacement is 0.026213249757982896
The coef for horsepower is -0.01826325248144899
The coef for weight is -0.007487326050213115
The coef for acceleration is 0.05036896947442574
The coef for model_year is 0.8470062938903152
The coef for origin is 1.5174528285653759

In [106]:
#for ridge regression evalutaion
Y_pred_ridge = ridge_regression_model.predict(X_test)
r2_ridge = r2_score(Y_test , Y_pred_ridge)
print(f"The R square of ridge regression {r2_ridge}")

The R square of ridge regression 0.8348084889168358

In [107]:
#we dont see much variation in coeff of ridge regression as compared to linear regression

In [108]:
#Lasso regression
from sklearn.linear_model import Lasso

In [109]:
lasso_regression_model = Lasso(alpha = 0.5)
lasso_regression_model

Lasso(alpha=0.5)

In [112]:
lasso_regression_model.fit(X_train , Y_train)

Lasso(alpha=0.5)

In [114]:
for i , col_name in enumerate(X_train.columns):
    print(f'The coef for {col_name} is {lasso_regression_model.coef_[i]}')

The coef for cylinders is -0.0
The coef for displacement is 0.006208198888300375
The coef for horsepower is -0.011058382987169579
The coef for weight is -0.00698267316802309
The coef for acceleration is 0.0
The coef for model_year is 0.7446549520038191
The coef for origin is 0.0

In [115]:
#three features coefficient is 0, lasso helps in feature selection

In [117]:
Y_pred_lasso = lasso_regression_model.predict(X_test)
r2_lasso = r2_score(Y_test , Y_pred_lasso)
print(f'The r square of lasso regression is {r2_lasso}')

The r square of lasso regression is 0.8277934716635554

In [118]:
#Elastic Net

from sklearn.linear_model import ElasticNet
elasticnet_regression_model = ElasticNet(alpha =  1, l1_ratio = 0.5 )
elasticnet_regression_model.fit(X_train , Y_train)

ElasticNet(alpha=1)

In [121]:
for i , col_name in enumerate(X_train.columns):
    print(f' The coef for {col_name} is {elasticnet_regression_model.coef_[i]}')

 The coef for cylinders is -0.0
 The coef for displacement is 0.0058888699536675535
 The coef for horsepower is -0.012403874933570123
 The coef for weight is -0.00693455051625763
 The coef for acceleration is 0.0
 The coef for model_year is 0.7133150744603872
 The coef for origin is 0.0

In [122]:
Y_pred_elastic = elasticnet_regression_model.predict(X_test)
r2_elastic = r2_score(Y_test , Y_pred_elastic)
print(f'The r square of elastic regression is {r2_elastic}')

The r square of elastic regression is 0.8284840073256805

In [123]:
#regularisation with crossvalidation 
from sklearn.linear_model import LassoCV
lasso_cv = LassoCV(cv = 5, verbose=2)
lasso_cv

LassoCV(cv=5, verbose=2)

In [125]:
lasso_cv.fit(X_train ,Y_train)

Path: 000 out of 100
Path: 001 out of 100
Path: 002 out of 100
Path: 003 out of 100
Path: 004 out of 100
Path: 005 out of 100
Path: 006 out of 100
Path: 007 out of 100
Path: 008 out of 100
Path: 009 out of 100
Path: 010 out of 100
Path: 011 out of 100
Path: 012 out of 100
Path: 013 out of 100
Path: 014 out of 100
Path: 015 out of 100
Path: 016 out of 100
Path: 017 out of 100
Path: 018 out of 100
Path: 019 out of 100
Path: 020 out of 100
Path: 021 out of 100
Path: 022 out of 100
Path: 023 out of 100
Path: 024 out of 100
Path: 025 out of 100
Path: 026 out of 100
Path: 027 out of 100
Path: 028 out of 100
Path: 029 out of 100
Path: 030 out of 100
Path: 031 out of 100
Path: 032 out of 100
Path: 033 out of 100
Path: 034 out of 100
Path: 035 out of 100
Path: 036 out of 100
Path: 037 out of 100
Path: 038 out of 100
Path: 039 out of 100
Path: 040 out of 100
Path: 041 out of 100
Path: 042 out of 100
Path: 043 out of 100
Path: 044 out of 100
Path: 045 out of 100
Path: 046 out of 100
Path: 047 out of 100
Path: 048 out of 100
Path: 049 out of 100
Path: 050 out of 100
Path: 051 out of 100
Path: 052 out of 100
Path: 053 out of 100
Path: 054 out of 100
Path: 055 out of 100
Path: 056 out of 100
Path: 057 out of 100
Path: 058 out of 100
Path: 059 out of 100
Path: 060 out of 100
Path: 061 out of 100
Path: 062 out of 100
Path: 063 out of 100
Path: 064 out of 100
Path: 065 out of 100
Path: 066 out of 100
Path: 067 out of 100
Path: 068 out of 100
Path: 069 out of 100
Path: 070 out of 100
Path: 071 out of 100
Path: 072 out of 100
Path: 073 out of 100
Path: 074 out of 100
Path: 075 out of 100
Path: 076 out of 100
Path: 077 out of 100
Path: 078 out of 100
Path: 079 out of 100
Path: 080 out of 100
Path: 081 out of 100
Path: 082 out of 100
Path: 083 out of 100
Path: 084 out of 100
Path: 085 out of 100
Path: 086 out of 100
Path: 087 out of 100
Path: 088 out of 100
Path: 089 out of 100
Path: 090 out of 100
Path: 091 out of 100
Path: 092 out of 100
Path: 093 out of 100
Path: 094 out of 100
Path: 095 out of 100
Path: 096 out of 100
Path: 097 out of 100
Path: 098 out of 100
Path: 099 out of 100
Path: 000 out of 100
Path: 001 out of 100
Path: 002 out of 100
Path: 003 out of 100
Path: 004 out of 100
Path: 005 out of 100
Path: 006 out of 100
Path: 007 out of 100
Path: 008 out of 100
Path: 009 out of 100
Path: 010 out of 100
Path: 011 out of 100
Path: 012 out of 100
Path: 013 out of 100
Path: 014 out of 100
Path: 015 out of 100
Path: 016 out of 100
Path: 017 out of 100
Path: 018 out of 100
Path: 019 out of 100
Path: 020 out of 100
Path: 021 out of 100
Path: 022 out of 100
Path: 023 out of 100
Path: 024 out of 100
Path: 025 out of 100
Path: 026 out of 100
Path: 027 out of 100
Path: 028 out of 100
Path: 029 out of 100
Path: 030 out of 100
Path: 031 out of 100
Path: 032 out of 100
Path: 033 out of 100
Path: 034 out of 100
Path: 035 out of 100
Path: 036 out of 100
Path: 037 out of 100
Path: 038 out of 100
Path: 039 out of 100
Path: 040 out of 100
Path: 041 out of 100
Path: 042 out of 100
Path: 043 out of 100
Path: 044 out of 100
Path: 045 out of 100
Path: 046 out of 100
Path: 047 out of 100
Path: 048 out of 100
Path: 049 out of 100
Path: 050 out of 100
Path: 051 out of 100
Path: 052 out of 100
Path: 053 out of 100
Path: 054 out of 100
Path: 055 out of 100
Path: 056 out of 100
Path: 057 out of 100
Path: 058 out of 100
Path: 059 out of 100
Path: 060 out of 100
Path: 061 out of 100
Path: 062 out of 100
Path: 063 out of 100
Path: 064 out of 100
Path: 065 out of 100
Path: 066 out of 100
Path: 067 out of 100
Path: 068 out of 100
Path: 069 out of 100
Path: 070 out of 100
Path: 071 out of 100
Path: 072 out of 100
Path: 073 out of 100
Path: 074 out of 100
Path: 075 out of 100
Path: 076 out of 100
Path: 077 out of 100
Path: 078 out of 100
Path: 079 out of 100
Path: 080 out of 100
Path: 081 out of 100
Path: 082 out of 100
Path: 083 out of 100
Path: 084 out of 100
Path: 085 out of 100
Path: 086 out of 100
Path: 087 out of 100
Path: 088 out of 100
Path: 089 out of 100
Path: 090 out of 100
Path: 091 out of 100
Path: 092 out of 100
Path: 093 out of 100
Path: 094 out of 100
Path: 095 out of 100
Path: 096 out of 100
Path: 097 out of 100
Path: 098 out of 100
Path: 099 out of 100
Path: 000 out of 100
Path: 001 out of 100
Path: 002 out of 100
Path: 003 out of 100
Path: 004 out of 100
Path: 005 out of 100
Path: 006 out of 100
Path: 007 out of 100
Path: 008 out of 100
Path: 009 out of 100
Path: 010 out of 100
Path: 011 out of 100
Path: 012 out of 100
Path: 013 out of 100
Path: 014 out of 100
Path: 015 out of 100
Path: 016 out of 100
Path: 017 out of 100
Path: 018 out of 100
Path: 019 out of 100
Path: 020 out of 100
Path: 021 out of 100
Path: 022 out of 100
Path: 023 out of 100
Path: 024 out of 100
Path: 025 out of 100
Path: 026 out of 100
Path: 027 out of 100
Path: 028 out of 100
Path: 029 out of 100
Path: 030 out of 100
Path: 031 out of 100
Path: 032 out of 100
Path: 033 out of 100
Path: 034 out of 100
Path: 035 out of 100
Path: 036 out of 100
Path: 037 out of 100
Path: 038 out of 100
Path: 039 out of 100
Path: 040 out of 100
Path: 041 out of 100
Path: 042 out of 100
Path: 043 out of 100
Path: 044 out of 100
Path: 045 out of 100
Path: 046 out of 100
Path: 047 out of 100
Path: 048 out of 100
Path: 049 out of 100
Path: 050 out of 100
Path: 051 out of 100
Path: 052 out of 100
Path: 053 out of 100
Path: 054 out of 100
Path: 055 out of 100
Path: 056 out of 100
Path: 057 out of 100
Path: 058 out of 100
Path: 059 out of 100
Path: 060 out of 100
Path: 061 out of 100
Path: 062 out of 100
Path: 063 out of 100
Path: 064 out of 100
Path: 065 out of 100
Path: 066 out of 100
Path: 067 out of 100
Path: 068 out of 100
Path: 069 out of 100
Path: 070 out of 100
Path: 071 out of 100
Path: 072 out of 100
Path: 073 out of 100
Path: 074 out of 100
Path: 075 out of 100
Path: 076 out of 100
Path: 077 out of 100
Path: 078 out of 100
Path: 079 out of 100
Path: 080 out of 100
Path: 081 out of 100
Path: 082 out of 100
Path: 083 out of 100
Path: 084 out of 100
Path: 085 out of 100
Path: 086 out of 100
Path: 087 out of 100
Path: 088 out of 100
Path: 089 out of 100
Path: 090 out of 100
Path: 091 out of 100
Path: 092 out of 100
Path: 093 out of 100
Path: 094 out of 100
Path: 095 out of 100
Path: 096 out of 100
Path: 097 out of 100
Path: 098 out of 100
Path: 099 out of 100
Path: 000 out of 100
Path: 001 out of 100
Path: 002 out of 100
Path: 003 out of 100
Path: 004 out of 100
Path: 005 out of 100
Path: 006 out of 100
Path: 007 out of 100
Path: 008 out of 100
Path: 009 out of 100
Path: 010 out of 100
Path: 011 out of 100
Path: 012 out of 100
Path: 013 out of 100
Path: 014 out of 100
Path: 015 out of 100
Path: 016 out of 100
Path: 017 out of 100
Path: 018 out of 100
Path: 019 out of 100
Path: 020 out of 100
Path: 021 out of 100
Path: 022 out of 100
Path: 023 out of 100
Path: 024 out of 100
Path: 025 out of 100
Path: 026 out of 100
Path: 027 out of 100
Path: 028 out of 100
Path: 029 out of 100
Path: 030 out of 100
Path: 031 out of 100
Path: 032 out of 100
Path: 033 out of 100
Path: 034 out of 100
Path: 035 out of 100
Path: 036 out of 100
Path: 037 out of 100
Path: 038 out of 100
Path: 039 out of 100
Path: 040 out of 100
Path: 041 out of 100
Path: 042 out of 100
Path: 043 out of 100
Path: 044 out of 100
Path: 045 out of 100
Path: 046 out of 100
Path: 047 out of 100
Path: 048 out of 100
Path: 049 out of 100
Path: 050 out of 100
Path: 051 out of 100
Path: 052 out of 100
Path: 053 out of 100
Path: 054 out of 100
Path: 055 out of 100
Path: 056 out of 100
Path: 057 out of 100
Path: 058 out of 100
Path: 059 out of 100
Path: 060 out of 100
Path: 061 out of 100
Path: 062 out of 100
Path: 063 out of 100
Path: 064 out of 100
Path: 065 out of 100
Path: 066 out of 100
Path: 067 out of 100
Path: 068 out of 100
Path: 069 out of 100
Path: 070 out of 100
Path: 071 out of 100
Path: 072 out of 100
Path: 073 out of 100
Path: 074 out of 100
Path: 075 out of 100
Path: 076 out of 100
Path: 077 out of 100
Path: 078 out of 100
Path: 079 out of 100
Path: 080 out of 100
Path: 081 out of 100
Path: 082 out of 100
Path: 083 out of 100
Path: 084 out of 100
Path: 085 out of 100
Path: 086 out of 100
Path: 087 out of 100
Path: 088 out of 100
Path: 089 out of 100
Path: 090 out of 100
Path: 091 out of 100
Path: 092 out of 100
Path: 093 out of 100
Path: 094 out of 100
Path: 095 out of 100
Path: 096 out of 100
Path: 097 out of 100
Path: 098 out of 100
Path: 099 out of 100
Path: 000 out of 100
Path: 001 out of 100
Path: 002 out of 100
Path: 003 out of 100
Path: 004 out of 100
Path: 005 out of 100
Path: 006 out of 100
Path: 007 out of 100
Path: 008 out of 100
Path: 009 out of 100
Path: 010 out of 100
Path: 011 out of 100
Path: 012 out of 100
Path: 013 out of 100
Path: 014 out of 100
Path: 015 out of 100
Path: 016 out of 100
Path: 017 out of 100
Path: 018 out of 100
Path: 019 out of 100
Path: 020 out of 100
Path: 021 out of 100
Path: 022 out of 100
Path: 023 out of 100
Path: 024 out of 100
Path: 025 out of 100
Path: 026 out of 100
Path: 027 out of 100
Path: 028 out of 100
Path: 029 out of 100
Path: 030 out of 100
Path: 031 out of 100
Path: 032 out of 100
Path: 033 out of 100
Path: 034 out of 100
Path: 035 out of 100
Path: 036 out of 100
Path: 037 out of 100
Path: 038 out of 100
Path: 039 out of 100
Path: 040 out of 100
Path: 041 out of 100
Path: 042 out of 100
Path: 043 out of 100
Path: 044 out of 100
Path: 045 out of 100
Path: 046 out of 100
Path: 047 out of 100
Path: 048 out of 100
Path: 049 out of 100
Path: 050 out of 100
Path: 051 out of 100
Path: 052 out of 100
Path: 053 out of 100
Path: 054 out of 100
Path: 055 out of 100
Path: 056 out of 100
Path: 057 out of 100
Path: 058 out of 100
Path: 059 out of 100
Path: 060 out of 100
Path: 061 out of 100
Path: 062 out of 100
Path: 063 out of 100
Path: 064 out of 100
Path: 065 out of 100
Path: 066 out of 100
Path: 067 out of 100
Path: 068 out of 100
Path: 069 out of 100
Path: 070 out of 100
Path: 071 out of 100
Path: 072 out of 100
Path: 073 out of 100
Path: 074 out of 100
Path: 075 out of 100
Path: 076 out of 100
Path: 077 out of 100
Path: 078 out of 100
Path: 079 out of 100
Path: 080 out of 100
Path: 081 out of 100
Path: 082 out of 100
Path: 083 out of 100
Path: 084 out of 100
Path: 085 out of 100
Path: 086 out of 100
Path: 087 out of 100
Path: 088 out of 100
Path: 089 out of 100
Path: 090 out of 100
Path: 091 out of 100
Path: 092 out of 100
Path: 093 out of 100
Path: 094 out of 100
Path: 095 out of 100
Path: 096 out of 100
Path: 097 out of 100
Path: 098 out of 100
Path: 099 out of 100

LassoCV(cv=5, verbose=2)

In [127]:
Y_pred= lasso_cv.predict(X_test)
r2_lasso = r2_score(Y_test , Y_pred)
print(f'The r square value of Lasso CV is {r2_lasso}')

The r square value of Lasso CV is 0.808280598384475

In [129]:
from sklearn.linear_model import RidgeCV
ridge_cv = RidgeCV( cv = 5)
ridge_cv.fit(X_train , Y_train)

RidgeCV(cv=5)

In [130]:
Y_pred = ridge_cv.predict(X_test)
r2_ridge_cv = r2_score(Y_test , Y_pred)
print(f'The r square value for ridge_cv is {r2_ridge_cv}')

The r square value for ridge_cv is 0.8354145247502054

In [131]:
ridge_cv.get_params()

{'alpha_per_target': False,
 'alphas': (0.1, 1.0, 10.0),
 'cv': 5,
 'fit_intercept': True,
 'gcv_mode': None,
 'scoring': None,
 'store_cv_results': None,
 'store_cv_values': 'deprecated'}

In [132]:
from sklearn.linear_model import ElasticNetCV

In [133]:
elastic_net_cv = ElasticNetCV( cv = 5)
elastic_net_cv.fit(X_train , Y_train)

ElasticNetCV(cv=5)